/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QfybJ5m0kyZ
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { CardContent, Card } from "@/components/ui/card";

export function SearchSection() {
	return (
		<div className="bg-gray-900 min-h-screen text-white">
			<div className="container mx-auto px-4 py-8">
				<h1 className="text-5xl font-bold">Search the Web</h1>
				<p className="text-xl mt-2 mb-6">Enter your search query below.</p>
				<div className="relative mb-6">
					<MicroscopeIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500" />
					<Input
						className="pl-12 pr-4 py-3 w-full rounded-md bg-gray-800 text-white border border-gray-700"
						placeholder="Search the web"
						type="text"
					/>
				</div>
				<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
					<Card className="w-full bg-gray-800">
						<CardContent>
							<div className="flex flex-col items-center">
								<img
									alt="Placeholder"
									className="mb-4"
									height="200"
									src="/placeholder.svg"
									style={{
										aspectRatio: "200/200",
										objectFit: "cover",
									}}
									width="200"
								/>
								<h2 className="text-lg font-semibold mb-2">Card title</h2>
								<p className="text-sm mb-4">
									This is a wider card with supporting text below as a natural
									lead-in to additional content. This content is a little bit
									longer.
								</p>
								<Button variant="outline">Read more</Button>
							</div>
						</CardContent>
					</Card>
					<Card className="w-full bg-gray-800">
						<CardContent>
							<div className="flex flex-col items-center">
								<img
									alt="Placeholder"
									className="mb-4"
									height="200"
									src="/placeholder.svg"
									style={{
										aspectRatio: "200/200",
										objectFit: "cover",
									}}
									width="200"
								/>
								<h2 className="text-lg font-semibold mb-2">Card title</h2>
								<p className="text-sm mb-4">
									This is a wider card with supporting text below as a natural
									lead-in to additional content. This content is a little bit
									longer.
								</p>
								<Button variant="outline">Read more</Button>
							</div>
						</CardContent>
					</Card>
					<Card className="w-full bg-gray-800">
						<CardContent>
							<div className="flex flex-col items-center">
								<img
									alt="Placeholder"
									className="mb-4"
									height="200"
									src="/placeholder.svg"
									style={{
										aspectRatio: "200/200",
										objectFit: "cover",
									}}
									width="200"
								/>
								<h2 className="text-lg font-semibold mb-2">Card title</h2>
								<p className="text-sm mb-4">
									This is a wider card with supporting text below as a natural
									lead-in to additional content. This content is a little bit
									longer.
								</p>
								<Button variant="outline">Read more</Button>
							</div>
						</CardContent>
					</Card>
					<Card className="w-full bg-gray-800">
						<CardContent>
							<div className="flex flex-col items-center">
								<img
									alt="Placeholder"
									className="mb-4"
									height="200"
									src="/placeholder.svg"
									style={{
										aspectRatio: "200/200",
										objectFit: "cover",
									}}
									width="200"
								/>
								<h2 className="text-lg font-semibold mb-2">Card title</h2>
								<p className="text-sm mb-4">
									This is a wider card with supporting text below as a natural
									lead-in to additional content. This content is a little bit
									longer.
								</p>
								<Button variant="outline">Read more</Button>
							</div>
						</CardContent>
					</Card>
				</div>
				<div className="flex justify-center space-x-8">
					<Button className="bg-[#1e1e1e] text-white py-2 px-4 rounded-md">
						Previous
					</Button>
					<Button className="bg-[#1e1e1e] text-white py-2 px-4 rounded-md">
						1
					</Button>
					<Button className="bg-[#1e1e1e] text-white py-2 px-4 rounded-md">
						2
					</Button>
					<Button className="bg-[#1e1e1e] text-white py-2 px-4 rounded-md">
						3
					</Button>
					<Button className="bg-[#1e1e1e] text-white py-2 px-4 rounded-md">
						4
					</Button>
					<Button className="bg-[#1e1e1e] text-white py-2 px-4 rounded-md">
						Next
					</Button>
				</div>
			</div>
		</div>
	);
}

function MicroscopeIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round">
			<path d="M6 18h8" />
			<path d="M3 22h18" />
			<path d="M14 22a7 7 0 1 0 0-14h-1" />
			<path d="M9 14h2" />
			<path d="M9 12a2 2 0 0 1-2-2V6h6v4a2 2 0 0 1-2 2Z" />
			<path d="M12 6V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3" />
		</svg>
	);
}
